version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    container_name: hospitality_postgres
    restart: always
    environment:
      POSTGRES_DB: hospitality_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Cache & Event Queue Broker
  redis:
    image: redis:7-alpine
    container_name: hospitality_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  # Local S3 Compatible File Storage
  minio:
    image: minio/minio:latest
    container_name: hospitality_minio
    restart: always
    ports:
      - '9000:9000' # API Port
      - '9001:9001' # Console UI Port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    entrypoint: sh
    command: -c "minio server /data --console-address ':9001'"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  redis_data:
  minio_data:
